### ISSUE TITLE
To-do list 

### ISSUE THREAD

**Issue by currocam** [currocam/HMMERutils#2]
## Bugs to solve before getting a minimum version

- [x] There can be more than one row per homologous sequence. The exact sequence can have more than one homologous domain or, if searched against the PDB, more than one PDB. Right now there is one row per homologous domain (okay) but the variables referring to the domain are in a single list. New columns have to be added to each row of that list. Also, when dealing with pdbs, new rows would have to be created with each PDB. The same thing that happens to hits.domains happens to hits.seqs I propose to create a new function extract_from_hmmer that accepts the column name (default hits.domains). 

An example of how to obtain sample data
```r
BiocManager::install("currocam/HMMERutils")
library("HMMERutils")
fasta_2abl <- paste0(
    "MGPSENDPNLFVALYDFVASGDNTLSITKGEKLRVLGYNHNGEWCEAQTKNGQGW",
    "VPSNYITPVNSLEKHSWYHGPVSRNAAEYLLSSGINGSFLVRESESSPGQRSISL",
    "RYEGRVYHYRINTASDGKLYVSSESRFNTLAELVHHHSTVADGLITTLHYPAP"
)
data <- search_phmmer(seq = fasta_2abl, seqdb = "pdb") %>%
    add_sequences_to_hmmer_tbl() %>%
    add_taxa_to_hmmer_tbl() %>%
    add_physicochemical_properties_to_HMMER_tbl()
```

The only R library that has implemented something similar is bio3d and it doesn't work well for a general case (only to search for pdbs, which is what they wanted it for). Anyway, the [example here of how they have implemented it.](https://github.com/cran/bio3d/blob/master/R/hmmer.R) It does not pass Bioconductor standards. 

## Bugs to solve before submitting to Bioconductor

- [x] Fix the continuous integration workflow that checks if the library meets the Bioconductor requirements. Example of failed  [GitHub action](https://github.com/currocam/HMMERutils/actions/runs/3311622408)
- [x] Bioconductor requires that 80% of the functions have examples that can be run. These examples act as tests in the library (something like doctest in Python). It must be executed in a short time and with low CPU use. This library depends on HMMER web server and NCBI database,  so time is too long when I add them. This same problem also applies to the vignette, although we could include it separately. 
- [x] BiocViews bug fix:  Checking for non-trivial biocViews... * ERROR: Add biocViews other than Software

## Things that would be nice to add to the library 

- [x] Add a function to filter out the significant results from those that are not. In the HMMER manual, it is indicated that it is necessary to consider both the E-values of the sequences and the domains. It would be something like `filter_hits_by_evalue(data, by = c("hits" or "best domain))`

- [x] In the previous version, there was a function to calculate the pairwise distance matrix between sequences. It would be nice to take a look at it to see if it can be made more efficient.
- [x] Right now the library does not accept paged responses. This is important for jackhmmer (which is an iterative search and each page is an iteration). Also for when the number of sequences exceeds a maximum (also not handled by the web server). It would be great to implement either. [An example from API manual](https://hmmer-web-docs.readthedocs.io/en/latest/api.html#jackhmmer)
- [x] I have been writing unit tests using testthat and httptest for mocking. Some functions don't have unit tests because I didn't know how to mock them, it would be interesting to see if they can be added.
